from app.domain.enums import CauseCategory


CAUSE_KEYWORDS: dict[CauseCategory, list[str]] = {
    CauseCategory.WORKPLACE_DESIGN: [
        "layout",
        "workspace",
        "design",
        "access",
        "narrow space",
        "poor visibility",
        "blind spot",
        "workstation design",
        "unsafe design",
    ],
    CauseCategory.HUMAN_FACTORS: [
        "fatigue",
        "inattention",
        "distraction",
        "forgot",
        "mistake",
        "human error",
        "rushed",
        "careless",
        "not paying attention",
    ],
    CauseCategory.ORGANIZATION: [
        "planning",
        "staffing",
        "coordination",
        "management decision",
        "scheduling",
        "workload",
        "understaffed",
        "organization",
    ],
    CauseCategory.HOUSEKEEPING: [
        "clutter",
        "mess",
        "debris",
        "dirty",
        "unclean",
        "spill not cleaned",
        "poor housekeeping",
        "obstruction",
    ],
    CauseCategory.PROCEDURES: [
        "procedure",
        "instruction",
        "sop",
        "work instruction",
        "step was skipped",
        "not followed procedure",
        "missing procedure",
        "incorrect procedure",
    ],
    CauseCategory.MAINTENANCE_MANAGEMENT: [
        "maintenance",
        "inspection overdue",
        "service overdue",
        "not maintained",
        "wear and tear",
        "broken equipment",
        "repair delayed",
        "preventive maintenance",
    ],
    CauseCategory.COMPETENCES: [
        "training",
        "not trained",
        "lack of training",
        "competence",
        "qualification",
        "unfamiliar",
        "inexperienced",
        "did not know",
    ],
    CauseCategory.PPE: [
        "ppe",
        "gloves",
        "helmet",
        "goggles",
        "face shield",
        "safety shoes",
        "protective equipment",
        "no ppe",
        "missing ppe",
    ],
    CauseCategory.COMMUNICATION: [
        "communication",
        "miscommunication",
        "not informed",
        "unclear message",
        "handover",
        "no warning",
        "not communicated",
        "unclear instruction",
    ],
    CauseCategory.PEDESTRIAN: [
        "pedestrian",
        "walking path",
        "walkway",
        "person walking",
        "crossing",
        "foot traffic",
    ],
    CauseCategory.FACILITIES_EQUIPMENT: [
        "facility",
        "equipment failure",
        "broken tool",
        "damaged equipment",
        "faulty equipment",
        "machine issue",
        "infrastructure",
        "building issue",
    ],
}